name: Main

on:
  - push
  - workflow_dispatch

jobs:
  primary:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Show the readme
        run: cat README.md
